[phases.setup]
# Node 22 van a 24.11-ben
nixPkgs = ["nodejs_22", "openssl", "sqlite", "python3", "gnumake", "gcc", "pkg-config"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]
nixpkgsArchive = "nixos-24.11"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --include=dev"]
cacheDirectories = ["/root/.npm"]
paths = ["/app/node_modules/.bin"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run prisma:generate", "npm run build"]
cacheDirectories = ["node_modules/.cache"]

[start]
# ha szeretnéd, futtasd a migrációkat induláskor:
# cmd = "npm run prisma:deploy && node build/index.js"
cmd = "node build/index.js"
