[phases.setup]
nixPkgs = ["nodejs_24", "openssl", "sqlite", "bash", "curl", "wget"]
nixpkgsArchive = "<IDE ÍRD AZ ÚJ NIXPKGS COMMIT HASH-T>"  # pl. a nixos-24.11 vagy nixos-unstable aktuális commitja

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[start]
cmd = "npm run start"