# nixpacks.toml

# A buildhez szükséges csomagok (Node 20, OpenSSL a Prisma engine-hez, sqlite, bash)
[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "sqlite", "bash"]

# Telepítés: kelleni fognak a devDependenciák is (Vite, SvelteKit stb.),
# ezért --include=dev még akkor is, ha NODE_ENV=production lesz futáskor.
[phases.install]
cmds = ["npm ci --include=dev"]

# Build: Prisma client + SvelteKit build (nálad a `npm run build` Vite-et hív)
[phases.build]
cmds = [
  "npm run prisma:generate",
  "npm run build"
]

# Futtatás: migrációk, opcionális seed, majd indul az adapter-node szerver
[processes.web]
command = "bash -lc 'export NODE_ENV=production; export PORT=${PORT:-3000}; npm run prisma:deploy && if [ \"${RUN_SEED}\" = \"true\" ]; then npx prisma db seed; fi; node build'"
