# nixpacks.toml

[phases.setup]
# -> Node 22-re váltunk, így megfelel a plugin verziókövetelményének
nixPkgs = ["nodejs_22", "openssl", "sqlite", "bash", "curl", "wget"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run prisma:generate", "npm run build"]

[processes.web]
command = "bash -lc 'export NODE_ENV=production; export PORT=${PORT:-3000}; npm run prisma:deploy && if [ \"${RUN_SEED}\" = \"true\" ]; then npx prisma db seed; fi; node build'"
